name: deploy
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker images
        run: |
          docker build -t erkizie/multi-client ./client
          docker build -t erkizie/multi-nginx ./nginx
          docker build -t erkizie/multi-server ./server
          docker build -t erkizie/multi-worker ./worker
          docker push erkizie/multi-client
          docker push erkizie/multi-nginx
          docker push erkizie/multi-server
          docker push erkizie/multi-worker
