name: Deploy
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
 
      - run: docker build -t erkizie/multi-client ./client
      - run: docker build -t erkizie/multi-nginx ./nginx
      - run: docker build -t erkizie/multi-server ./server
      - run: docker build -t erkizie/multi-worker ./worker
 
      - run: docker push erkizie/multi-client
      - run: docker push erkizie/multi-nginx
      - run: docker push erkizie/multi-server
      - run: docker push erkizie/multi-worker
